BLTHOME := ../../
include $(BLTHOME)make.conf

CFLAGS 		+= -fno-pic -fno-exceptions -fno-rtti
SRCS		:= Connection.cpp Window.cpp Canvas.cpp Button.cpp
LIBRARY		:= libwin.a
SHLIB		:= libwin.so

include $(BLTHOME)make.actions
