BLTHOME := ../../
include $(BLTHOME)make.conf

LIBRARY		:= libposix.a
SHLIB		:= libposix.so
SHLIB_MAJOR	:= 1
SHLIB_MINOR	:= 0
OBJS 		:= exec.o fdl.o vfs.o printf.o stdio.o getopt.o console.o

include $(BLTHOME)make.actions
