BLTHOME := ../../
include $(BLTHOME)make.conf

LIBRARY		:= libblt.a
SHLIB		:= libblt.so
SHLIB_MAJOR	:= 1
SHLIB_MINOR	:= 0
OBJS 		:= hash.o tell.o blkdev.o disk.o \
			namer.o Message.o Connection.o

include $(BLTHOME)make.actions
